Repository maqsoftware/Pehla-Class, pull requests merged in 2019-06, with the labels that each got.

#9 Fixed bubble button UI issue
  app/src/main/java/com/maq/xprize/onecourse/hindi/mainui/oc_playzone/OC_PlayZoneMenu.java
Labels: bug

#6 Updated OBB extraction logic to handle updates
  app/build.gradle
  app/src/main/java/com/maq/xprize/onecourse/hindi/mainui/DownloadExpansionFile.java
  app/src/main/java/com/maq/xprize/onecourse/hindi/mainui/MainActivity.java
  app/src/main/java/com/maq/xprize/onecourse/hindi/mainui/SplashScreenActivity.java
  app/src/main/java/com/maq/xprize/onecourse/hindi/utils/OBConnectionManager.java
  app/src/main/res/mipmap-hdpi/icon_child.png
  app/src/main/res/mipmap-mdpi/icon_child.png
  app/src/main/res/mipmap-xhdpi/icon_child.png
  app/src/main/res/mipmap-xxhdpi/icon_child.png
  app/src/main/res/mipmap-xxxhdpi/icon_child.png
  app/src/main/res/values/strings.xml
Labels: bug

#13 Fixed UI issue in Counting Section
  app/src/main/java/com/maq/xprize/onecourse/hindi/mainui/oc_countwhatyousee/OC_Cwys1.java
Labels: ui fix

#16 Added patch file logic to provide incremental updates
  app/build.gradle
  app/src/main/java/com/maq/xprize/onecourse/hindi/mainui/DownloadExpansionFile.java
  app/src/main/java/com/maq/xprize/onecourse/hindi/mainui/MainActivity.java
  app/src/main/java/com/maq/xprize/onecourse/hindi/mainui/SplashScreenActivity.java
  app/src/main/java/com/maq/xprize/onecourse/hindi/service/ExpansionDownloaderService.java
  app/src/main/java/com/maq/xprize/onecourse/hindi/utils/Zip.java
  app/src/main/res/layout/activity_splash_screen.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#45 Removed unnecessary permissions from Manifest file
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/maq/xprize/onecourse/hindi/mainui/DownloadExpansionFile.java
  app/src/main/java/com/maq/xprize/onecourse/hindi/mainui/MainActivity.java
  app/src/main/java/com/maq/xprize/onecourse/hindi/mainui/OBMainViewController.java
  app/src/main/java/com/maq/xprize/onecourse/hindi/mainui/SplashScreenActivity.java
  app/src/main/java/com/maq/xprize/onecourse/hindi/utils/OBAnalyticsManagerCommunity.java
  app/src/main/java/com/maq/xprize/onecourse/hindi/utils/OBAnalyticsManagerOnline.java
  app/src/main/java/com/maq/xprize/onecourse/hindi/utils/OBCameraManager.java
  app/src/main/java/com/maq/xprize/onecourse/hindi/utils/OBConfigManager.java
  app/src/main/java/com/maq/xprize/onecourse/hindi/utils/OBConnectionManager.java
  app/src/main/res/values/strings.xml
Labels: enhancement

#73 Fixed UI issue related to cropping of keyboard and overlapping of keyboard with text box
  .idea/misc.xml
  app/src/main/java/com/maq/xprize/onecourse/hindi/mainui/oc_playzone/OC_PlayZoneTypewrite.java
Labels: ui fix

#120 Added SD card support option for extraction of OBB file.
  .idea/misc.xml
  app/src/main/java/com/maq/xprize/onecourse/hindi/mainui/MainActivity.java
  app/src/main/java/com/maq/xprize/onecourse/hindi/mainui/SplashScreenActivity.java
  app/src/main/java/com/maq/xprize/onecourse/hindi/utils/OBConfigManager.java
  app/src/main/res/values/strings.xml
Labels: enhancement

#57 Firebase Integration to the App for storing the modules time
  app/build.gradle
  app/src/main/java/com/maq/xprize/onecourse/hindi/mainui/MainActivity.java
  app/src/main/java/com/maq/xprize/onecourse/hindi/mainui/OBMainViewController.java
  app/src/main/java/com/maq/xprize/onecourse/hindi/mainui/oc_lettersandsounds/OC_Mwyh1.java
  app/src/main/java/com/maq/xprize/onecourse/hindi/utils/OCM_FatController.java
  app/src/main/java/com/maq/xprize/onecourse/hindi/utils/OC_FatController.java
  app/src/main/res/values/strings.xml
  build.gradle
  downloader_library/build.gradle
  market_licensing/build.gradle
  zip_file/build.gradle
Labels: enhancement

#121 Added feature to download expansion files if deleted by user
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/maq/xprize/onecourse/hindi/mainui/DownloadExpansionFile.java
  app/src/main/java/com/maq/xprize/onecourse/hindi/mainui/MainActivity.java
  app/src/main/java/com/maq/xprize/onecourse/hindi/mainui/SplashScreenActivity.java
  app/src/main/java/com/maq/xprize/onecourse/hindi/service/ExpansionAlarmReceiver.java
  app/src/main/java/com/maq/xprize/onecourse/hindi/service/ExpansionDownloaderService.java
  app/src/main/java/com/maq/xprize/onecourse/hindi/utils/OBLocationManager.java
  app/src/main/java/com/maq/xprize/onecourse/hindi/utils/Zip.java
  app/src/main/res/layout/download_expansion_file.xml
  downloader_library/build.gradle
  downloader_library/src/main/java/com/google/android/vending/expansion/downloader/Constants.java
  downloader_library/src/main/java/com/google/android/vending/expansion/downloader/DownloadProgressInfo.java
  downloader_library/src/main/java/com/google/android/vending/expansion/downloader/DownloaderClientMarshaller.java
  downloader_library/src/main/java/com/google/android/vending/expansion/downloader/DownloaderServiceMarshaller.java
  downloader_library/src/main/java/com/google/android/vending/expansion/downloader/Helpers.java
  downloader_library/src/main/java/com/google/android/vending/expansion/downloader/IDownloaderClient.java
  downloader_library/src/main/java/com/google/android/vending/expansion/downloader/IDownloaderService.java
  downloader_library/src/main/java/com/google/android/vending/expansion/downloader/IStub.java
  downloader_library/src/main/java/com/google/android/vending/expansion/downloader/SystemFacade.java
  downloader_library/src/main/java/com/google/android/vending/expansion/downloader/impl/AndroidHttpClient.java
  downloader_library/src/main/java/com/google/android/vending/expansion/downloader/impl/CustomIntentService.java
  downloader_library/src/main/java/com/google/android/vending/expansion/downloader/impl/CustomNotificationFactory.java
  downloader_library/src/main/java/com/google/android/vending/expansion/downloader/impl/DownloadInfo.java
  downloader_library/src/main/java/com/google/android/vending/expansion/downloader/impl/DownloadNotification.java
  downloader_library/src/main/java/com/google/android/vending/expansion/downloader/impl/DownloadThread.java
  downloader_library/src/main/java/com/google/android/vending/expansion/downloader/impl/DownloaderService.java
  downloader_library/src/main/java/com/google/android/vending/expansion/downloader/impl/DownloadsDB.java
  downloader_library/src/main/java/com/google/android/vending/expansion/downloader/impl/HttpDateTime.java
  downloader_library/src/main/java/com/google/android/vending/expansion/downloader/impl/V14CustomNotification.java
  downloader_library/src/main/java/com/google/android/vending/expansion/downloader/impl/V3CustomNotification.java
  downloader_library/src/main/res/values/strings.xml
  market_licensing/build.gradle
  market_licensing/src/main/java/com/google/android/vending/licensing/LicenseChecker.java
Labels: enhancement
