Repository maqsoftware/Pehla-Class, pull requests merged in 2019-08, with the labels that each got.

#210 Update string resource file
  app/src/english/res/drawable-hdpi/wallpaper.jpg
  app/src/english/res/drawable-mdpi/wallpaper.jpg
  app/src/english/res/drawable-xhdpi/wallpaper.jpg
  app/src/english/res/drawable-xxhdpi/wallpaper.jpg
  app/src/english/res/drawable-xxxhdpi/wallpaper.jpg
  app/src/english/res/mipmap-hdpi/icon_child.png
  app/src/english/res/mipmap-mdpi/icon_child.png
  app/src/english/res/mipmap-xhdpi/icon_child.png
  app/src/english/res/mipmap-xxhdpi/icon_child.png
  app/src/english/res/mipmap-xxxhdpi/icon_child.png
  app/src/english/res/values/strings.xml
  app/src/hindi/res/drawable-hdpi/wallpaper.jpg
  app/src/hindi/res/drawable-mdpi/wallpaper.jpg
  app/src/hindi/res/drawable-xhdpi/wallpaper.jpg
  app/src/hindi/res/drawable-xxhdpi/wallpaper.jpg
  app/src/hindi/res/drawable-xxxhdpi/wallpaper.jpg
  app/src/hindi/res/mipmap-hdpi/icon_child.png
  app/src/hindi/res/mipmap-mdpi/icon_child.png
  app/src/hindi/res/mipmap-xhdpi/icon_child.png
  app/src/hindi/res/mipmap-xxhdpi/icon_child.png
  app/src/hindi/res/mipmap-xxxhdpi/icon_child.png
  app/src/hindi/res/values/strings.xml
  app/src/main/config/settings_community_enIN.plist
  app/src/main/java/com/maq/pehlaclass/mainui/DownloadExpansionFile.java
  app/src/main/java/com/maq/pehlaclass/mainui/SplashScreenActivity.java
  app/src/main/java/com/maq/pehlaclass/mainui/oc_listeninggame/OC_Lg3.java
  app/src/main/res/values/strings.xml
Labels: enhancement

#217 Update LICENSE
  LICENSE
Labels: Documentation, enhancement

#220 Fix google-services.json file issue and updated version code
  app/build.gradle
  app/src/main/java/com/maq/pehlaclass/service/ExpansionDownloaderService.java
  app/src/main/res/drawable-xxhdpi/wallpaper.jpg
  app/src/main/res/layout/activity_splash_screen.xml
Labels: bug, enhancement

#216 Update INSTALL.md and LOCALIZE.md
  BUILD.md
  INSTALL-STANDALONE.md
  INSTALL.md
  LOCALIZE.md
  README.md
  SETUP.md
Labels: Documentation
